import { Lobby } from "./storeTypes";

/**
 * Mock lobby data for testing the LobbyCoinScroller component
 * Features 12 different lobbies with:
 * - Various currency types (USD, BTC, EUR, GBP, JPY, COINS, GEMS, FREE)
 * - Different currency symbols ($, ₿, €, £, ¥, 🪙, 💎)
 * - Escalating entry fees from $0 to $100K
 * - Mix of free and premium lobby types
 * - Perfect for testing scroll functionality and visual variety
 */

export const lobbies: Lobby[] = [
  // {
  //   _id: "1",
  //   entryFee: 0,
  //   winAmount: 0,
  //   lobbyType: LOBBY_TYPE.FREE,
  //   currencySymbol: "",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "2",
  //   entryFee: 5,
  //   winAmount: 9,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "3",
  //   entryFee: 25,
  //   winAmount: 45,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "4",
  //   entryFee: 100,
  //   winAmount: 180,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "5",
  //   entryFee: 500,
  //   winAmount: 900,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "6",
  //   entryFee: 1000,
  //   winAmount: 1800,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "₿",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "7",
  //   entryFee: 2500,
  //   winAmount: 4500,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "€",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "8",
  //   entryFee: 5000,
  //   winAmount: 9000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "£",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "9",
  //   entryFee: 10000,
  //   winAmount: 18000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "¥",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "10",
  //   entryFee: 25000,
  //   winAmount: 45000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "🪙",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "11",
  //   entryFee: 50000,
  //   winAmount: 90000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "💎",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "12",
  //   entryFee: 100000,
  //   winAmount: 180000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_COINS,
  //   isActive: true,
  // },
  // {
  //   _id: "1",
  //   entryFee: 0,
  //   winAmount: 0,
  //   lobbyType: LOBBY_TYPE.FREE,
  //   currencySymbol: "",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "2",
  //   entryFee: 5,
  //   winAmount: 9,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "3",
  //   entryFee: 25,
  //   winAmount: 45,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "4",
  //   entryFee: 100,
  //   winAmount: 180,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "5",
  //   entryFee: 500,
  //   winAmount: 900,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "6",
  //   entryFee: 1000,
  //   winAmount: 1800,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "₿",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "7",
  //   entryFee: 2500,
  //   winAmount: 4500,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "€",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "8",
  //   entryFee: 5000,
  //   winAmount: 9000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "£",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "9",
  //   entryFee: 10000,
  //   winAmount: 18000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "¥",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "10",
  //   entryFee: 25000,
  //   winAmount: 45000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "🪙",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "11",
  //   entryFee: 50000,
  //   winAmount: 90000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "💎",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
  // {
  //   _id: "12",
  //   entryFee: 100000,
  //   winAmount: 180000,
  //   lobbyType: LOBBY_TYPE.PREMIUM,
  //   currencySymbol: "$",
  //   currencyCode: CURRENCY_CODES.PLAY_CASH,
  //   isActive: true,
  // },
];
