// === HeatWave PvP — Error Codes ===

export enum ErrorCode {
  // Auth
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED = 'AUTH_EXPIRED',

  // Queue
  ALREADY_IN_QUEUE = 'ALREADY_IN_QUEUE',
  NOT_IN_QUEUE = 'NOT_IN_QUEUE',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',

  // Game
  NOT_IN_ROOM = 'NOT_IN_ROOM',
  GAME_NOT_RUNNING = 'GAME_NOT_RUNNING',
  PLAYER_NOT_ALIVE = 'PLAYER_NOT_ALIVE',
  NO_USES_LEFT = 'NO_USES_LEFT',
  RATE_LIMITED = 'RATE_LIMITED',
  INVALID_ACTION = 'INVALID_ACTION',

  // General
  INVALID_MESSAGE = 'INVALID_MESSAGE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
