import { Assets, AssetsManifest } from "pixi.js";
import { Logger } from "./logger";
import { FONTS } from "../constants/typography";
import FontFaceObserver from "fontfaceobserver";

/** List of assets grouped in bundles, for dynamic loading */
let assetsManifest: AssetsManifest = { bundles: [] };

/** Store bundles already loaded */
const loadedBundles: string[] = [];

/** Check if a bundle exists in assetManifest  */
function checkBundleExists(bundle: string) {
  return !!assetsManifest.bundles.find((b) => b.name === bundle);
}

/** Load assets bundles that have not been loaded yet */
export async function loadBundles(bundles: string | string[]) {
  if (typeof bundles === "string") bundles = [bundles];

  // Check bundles requested if they exists
  for (const bundle of bundles) {
    if (!checkBundleExists(bundle)) {
      throw new Error(`[Assets] Invalid bundle: ${bundle}`);
    }
  }

  // Filter out bundles already loaded
  const loadList = bundles.filter((bundle) => !loadedBundles.includes(bundle));

  // Skip if there is no bundle left to be loaded
  if (!loadList.length) return;

  // Load bundles
  console.debug("[Assets] Load:", loadList.join(", "));
  await Assets.loadBundle(loadList);

  // Append loaded bundles to the loaded list
  loadedBundles.push(...loadList);
}

/** Check if all bundles are loaded, return false if any of them is not loaded yet  */
export function areBundlesLoaded(bundles: string[]) {
  for (const name of bundles) {
    // Return false if a single bundle is not present in the loaded list
    if (!loadedBundles.includes(name)) {
      return false;
    }
  }

  // All provided bundles are loaded
  return true;
}

/** Load the assets json manifest generated by assetpack */
async function fetchAssetsManifest(url: string) {
  const response = await fetch(url);
  const manifest = await response.json();
  if (!manifest.bundles) {
    throw new Error("[Assets] Invalid assets manifest");
  }
  return manifest;
}

/** Initialize and start background loading of all assets */
export async function initAssets() {
  // Check if Assets is already initialized (to avoid double initialization)
  if (
    !assetsManifest ||
    !assetsManifest.bundles ||
    assetsManifest.bundles.length === 0
  ) {
    // Load assets manifest
    assetsManifest = await fetchAssetsManifest("assets/assets-manifest.json");

    // Init PixiJS assets with this asset manifest
    await Assets.init({
      manifest: assetsManifest,
      basePath: "assets",
      // texturePreference: {
      //   // resolution: 5,
      //   format: ["png", "svg"],
      // },
    });
  }
}

export async function initFonts() {
  try {
    const alumniSans = new FontFaceObserver(FONTS.PRIMARY);
    const pridi = new FontFaceObserver(FONTS.SECONDARY);
    const inter = new FontFaceObserver(FONTS.THIRD);
    await Promise.all([
      alumniSans.load(null, 10000),
      pridi.load(null, 10000),
      inter.load(null, 10000),
    ]);
    Logger.info("All fonts loaded successfully");
  } catch (e) {
    Logger.error("Failed to load fonts:", e);
  }
}
