// === HeatWave PvP — Client Constants ===
// Re-export shared constants + client-only constants

export {
  TICK_INTERVAL,
  TICKS_PER_SECOND,
  BASE_HEAT_PER_TICK,
  HEAT_ACCELERATION,
  HEAT_JITTER_RANGE,
  HEAT_MAX,
  COOL_HEAT_REDUCTION,
  COOL_RATE_MODIFIER,
  COOL_DURATION,
  COOL_MAX_USES,
  BOOST_HEAT_INCREASE,
  BOOST_RATE_MODIFIER,
  BOOST_DURATION,
  BOOST_MAX_USES,
  BOOST_TIME_BONUS,
  PRIZE_POOL,
  STARTING_BALANCE,
  BET_AMOUNT,
  COUNTDOWN_SECONDS,
  TOTAL_PLAYERS,
} from '../shared/constants';

// Colors (client-only, not needed on server)
export const COLORS = {
  background: '#0a0a1a',
  backgroundLight: '#141432',
  surface: '#1a1a3e',
  surfaceLight: '#252560',
  accent: '#ff6b35',
  accentGlow: '#ff8c5a',
  cool: '#00d4ff',
  coolGlow: '#66e5ff',
  boost: '#ff4444',
  boostGlow: '#ff7777',
  exit: '#44ff44',
  exitGlow: '#88ff88',
  text: '#ffffff',
  textDim: '#888899',
  textMuted: '#555566',
  gold: '#ffd700',
  silver: '#c0c0c0',
  bronze: '#cd7f32',
  heatLow: '#00ff88',
  heatMid: '#ffaa00',
  heatHigh: '#ff3333',
  heatCritical: '#ff0000',
  bust: '#ff2222',
  alive: '#00dd66',
  exited: '#ffcc00',
} as const;
